### PR TITLE
Testing: Remove Urho

### PR DESCRIPTION
**Pull request by RuthgerD**
urho is not nice :)
Removes urho
Removes vehicle config code
Adds rapidjson stand alone instead of urhos one
Removes urho from ci
Fixes some cmake to be library friendly

### CODE REVIEW

**Comment by platisd** [comment]
If this is merged, will the project be functional/complete?

**Comment by RuthgerD** [comment]
> If this is merged, will the project be functional/complete?

Yes because this PR merges into `testing` not `master` :) we intend to keep master as is until we have something better for the frontend (e.g. my Godot rewrite). The plan is to have that in a [different repo](https://github.com/ItJustWorksTM/smce-gd/tree/testing) though, so thats why I wanted to remove urho so that I can just focus on the library side of this project.

Anyways until then I intend to have `testing` as the mainline develop branch, hence the PR so that its visible

**Comment by platisd** [comment]
Oh I didn't notice this wasn't going towards `master`. Nevermind then. :eyes:

**Comment by RuthgerD** [comment]
Closing in favor of [libSMCE](https://github.com/ItJustWorksTM/libSMCE/tree/preview)

**Pull request closed without merging**
